"""Add card_size field to Product

Revision ID: 422e58176fdc
Revises: 
Create Date: 2025-11-13 00:44:36.719841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '422e58176fdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_size', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.drop_column('card_size')

    # ### end Alembic commands ###
